### ISSUE TITLE
CORS issue still with Rarible

### ISSUE THREAD

**Issue by jeffscottward** [ethglobal/nfthack-support#3]
Trying this address does not work

https://api.rarible.com/protocol/ethereum/nft/indexer/v1/items?creator=0xc02624affa30299fa164e7176a37610835a923a7

**Comment by tenthirtyone** [comment]
Hey @jeffscottward taking a look

**Comment by tenthirtyone** [comment]
I am able to get this to load in the browser, and using curl and node-fetch. I see:

```
{"total":0,"continuation":"50","items":[]}
```

Could you tell me a little about how you're making the request?

**Comment by jeffscottward** [comment]
The issue was that it wasn't the staging URL
https://api-staging.rarible.com/protocol/ethereum/nft/indexer/v0.1/swagger/webjars/swagger-ui/index.html?configUrl=/protocol/ethereum/nft/indexer/v0.1/swagger/v3/api-docs/swagger-config#/
