### ISSUE TITLE
Can't access my team

### ISSUE THREAD

**Issue by kaigani** [ethglobal/nfthack-support#5]
Hi - I was late to send my request to join the hackathon, and there is a team that would like me to work with them.  Can I be given access?  I have a code for the dashboard already, just no login.

**Comment by p0unce** [comment]
Hey there! Sadly we are at capacity for this event and can't admit any more hackers. If you did not receive an acceptance from ETHGlobal we can't admit you. If you have any further questions reach out to us at hello@ethglobal.co.
